# -*- coding: utf-8 -*-
"""ia-2022-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1mNPqdxMlbRWa_vslCfE8wOOd4vCT6f
"""

# Função para impressão do tabuleiro
def imprime_tabuleiro(t):
  s = '''
  {} | {} | {}
--------------
  {} | {} | {}
--------------
  {} | {} | {}'''

  t2 = [i if i else ' ' for i in t]
  
  print (s.format(*t2))

# Função para impressão das casas disponíveis
def imprime_casas_disponiveis(t):
  s = '''
  {} | {} | {}
--------------
  {} | {} | {}
--------------
  {} | {} | {}'''

  t2 = [i if not t[i] else ' ' for i in range(len(t))]
  
  print (s.format(*t2))

# Retorna as casas disponíveis
def casas_disponiveis(t):
  return [i for i in range(len(t)) if not t[i]]

# Inicializações
from google.colab import output

tabuleiro = [None] * 9
jogador_vez = 'X'

# Jogo
for rodada in range(9):
  print ('\nTabuleiro:\n')
  imprime_tabuleiro(tabuleiro)

  print ('\nCasas disponíveis:\n')
  imprime_casas_disponiveis(tabuleiro)

  disponiveis = casas_disponiveis(tabuleiro)
  
  jogada = int(input('Informe a casa desejada:'))
  while jogada not in disponiveis:
    print ('Casa inválida!')
    jogada = int(input('Informe a casa desejada:'))
  
  tabuleiro[jogada] = jogador_vez

  jogador_vez = 'X' if jogador_vez == 'O' else 'O'

  output.clear()